# 03 Machine Learning Workflow dengan Scikit Learn

## Persiapan Dataset

### Load Sample Dataset: Iris Dataset

In [20]:
from sklearn.datasets import load_iris

iris = load_iris()

x = iris.data
y = iris.target

### Splitting Dataset: Training & Testing Set

In [21]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size=0.4,
                                                    random_state=1)

## Training Model

<li>Pada Scikit Learn, model machine learning dibentuk dari class yang dikenal dengan istilah estimator
<li>Setiap estimator akan mengimplementasikan dua method utama, yaitu fit() dan predict()
<li>Method fit() digunakan untuk melakukan training model
<li>method predict() digunakan untuk melakukan estimasi/prediksi dengan memanfaatkan trained model

In [22]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

## Evaluasi Model

In [23]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)
acc = accuracy_score(y_test, y_pred)
print(f'Accuracy: {acc}')

Accuracy: 0.9833333333333333


## Pemanfaatan Trained Model

In [24]:
data_baru = [[5,5,3,2],
            [2,4,3,5]]

preds = model.predict(data_baru)
preds

array([1, 2])

In [25]:
pred_species = [iris.target_names[p] for p in preds]
print(f'Hasil Prediksi: {pred_species}')

Hasil Prediksi: ['versicolor', 'virginica']


## Dump & Load Trained Model

### Dumping Model Machine Learning menjadi file joblib

In [26]:
import joblib

joblib.dump(model, 'iris_classifier_knn.joblib')

['iris_classifier_knn.joblib']

### Loading Model Machine Learning dari file joblib

In [27]:
production_model = joblib.load('iris_classifier_knn.joblib')

## Sample Data

In [28]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1,-1.9,5.5],
                       [-1.5,2.4,3.5],
                       [0.5,-7.9,5.6],
                       [5.9,2.3,-5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [29]:
sample_data.shape

(4, 3)

## Binarisation

In [30]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [31]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

## Scaling

In [32]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [33]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0,1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [34]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

## L1 Normalisation: Least Absolute Deviations
Referensi: https://en.wikipedia.org/wiki/Least_absolute_deviations

In [35]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [36]:
l1_normalised_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalised_data 

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

## L2 Normalisation: Least Squares
Referensi: https://en.wikipedia.org/wiki/Least_squares

In [37]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [38]:
l2_normalised_data = preprocessing.normalize(sample_data, norm='l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])